from code_generation.quantity import NanoAODQuantity

run = NanoAODQuantity("run")
luminosityBlock = NanoAODQuantity("luminosityBlock")
event = NanoAODQuantity("event")
LHE_Njets = NanoAODQuantity("LHE_Njets")
prefireWeight = NanoAODQuantity("L1PreFiringWeight_Nom")

Tau_pt = NanoAODQuantity("Tau_pt")
Tau_eta = NanoAODQuantity("Tau_eta")
Tau_phi = NanoAODQuantity("Tau_phi")
Tau_mass = NanoAODQuantity("Tau_mass")
Tau_dz = NanoAODQuantity("Tau_dz")
Tau_dxy = NanoAODQuantity("Tau_dxy")
Tau_charge = NanoAODQuantity("Tau_charge")
Tau_decayMode = NanoAODQuantity("Tau_decayMode")
Tau_genMatch = NanoAODQuantity("Tau_genPartFlav")
Tau_IDraw = NanoAODQuantity("Tau_rawDeepTau2017v2p1VSjet")
Tau_indexToGen = NanoAODQuantity("Tau_genPartIdx")
Tau_associatedJet = NanoAODQuantity("Tau_jetIdx")
Tau_ID_vsJet = NanoAODQuantity("Tau_idDeepTau2017v2p1VSjet")
Tau_ID_vsEle = NanoAODQuantity("Tau_idDeepTau2017v2p1VSe")
Tau_ID_vsMu = NanoAODQuantity("Tau_idDeepTau2017v2p1VSmu")

boostedTau_pt = NanoAODQuantity("boostedTau_pt")
boostedTau_eta = NanoAODQuantity("boostedTau_eta")
boostedTau_phi = NanoAODQuantity("boostedTau_phi")
boostedTau_mass = NanoAODQuantity("boostedTau_mass")
boostedTau_decayMode = NanoAODQuantity("boostedTau_decayMode")
boostedTau_charge = NanoAODQuantity("boostedTau_charge")
boostedTau_iso_ID = NanoAODQuantity("boostedTau_idMVAoldDM2017v2")
boostedTau_iso_IDraw = NanoAODQuantity("boostedTau_rawMVAoldDM2017v2")
boostedTau_antiEle_ID = NanoAODQuantity("boostedTau_idAntiEle2018")
boostedTau_antiMu_ID = NanoAODQuantity("boostedTau_idAntiMu")
boostedTau_associatedJet = NanoAODQuantity("boostedTau_jetIdx")
boostedTau_genMatch = NanoAODQuantity("boostedTau_genPartFlav")

Muon_pt = NanoAODQuantity("Muon_pt")
Muon_eta = NanoAODQuantity("Muon_eta")
Muon_phi = NanoAODQuantity("Muon_phi")
Muon_mass = NanoAODQuantity("Muon_mass")
Muon_iso = NanoAODQuantity("Muon_pfRelIso04_all")
Muon_dz = NanoAODQuantity("Muon_dz")
Muon_dxy = NanoAODQuantity("Muon_dxy")
Muon_charge = NanoAODQuantity("Muon_charge")
Muon_genMatch = NanoAODQuantity("Muon_genPartFlav")
Muon_indexToGen = NanoAODQuantity("Muon_genPartIdx")
Muon_id_medium = NanoAODQuantity("Muon_mediumId")
Muon_id_tight = NanoAODQuantity("Muon_tightId")
Muon_id_loose = NanoAODQuantity("Muon_looseId")
Muon_isGlobal = NanoAODQuantity("Muon_isGlobal")
Muon_nStations = NanoAODQuantity("Muon_nStations")
Muon_nTrackerLayers = NanoAODQuantity("Muon_nTrackerLayers")
Muon_ptErr = NanoAODQuantity("Muon_ptErr")

Electron_pt = NanoAODQuantity("Electron_pt")
Electron_eta = NanoAODQuantity("Electron_eta")
Electron_dxy = NanoAODQuantity("Electron_dxy")
Electron_dz = NanoAODQuantity("Electron_dz")
Electron_phi = NanoAODQuantity("Electron_phi")
Electron_mass = NanoAODQuantity("Electron_mass")
Electron_iso = NanoAODQuantity("Electron_pfRelIso03_all")
Electron_charge = NanoAODQuantity("Electron_charge")
Electron_indexToGen = NanoAODQuantity("Electron_genPartIdx")
Electron_IDWP90 = NanoAODQuantity("Electron_mvaFall17V2noIso_WP90")
Electron_IDWP80 = NanoAODQuantity("Electron_mvaFall17V2noIso_WP80")

Photon_pt = NanoAODQuantity("Photon_pt")
Photon_eta = NanoAODQuantity("Photon_eta")
Photon_phi = NanoAODQuantity("Photon_phi")
Photon_mass = NanoAODQuantity("Photon_mass")
Photon_electronVeto = NanoAODQuantity("Photon_electronVeto")

GenJet_pt = NanoAODQuantity("GenJet_pt")
GenJet_eta = NanoAODQuantity("GenJet_eta")
GenJet_phi = NanoAODQuantity("GenJet_phi")
GenJet_mass = NanoAODQuantity("GenJet_mass")
GenJet_hadFlavour = NanoAODQuantity("GenJet_hadronFlavour")

Jet_eta = NanoAODQuantity("Jet_eta")
Jet_phi = NanoAODQuantity("Jet_phi")
Jet_pt = NanoAODQuantity("Jet_pt")
Jet_mass = NanoAODQuantity("Jet_mass")
Jet_area = NanoAODQuantity("Jet_area")
Jet_flavour = NanoAODQuantity("Jet_hadronFlavour")
Jet_rawFactor = NanoAODQuantity("Jet_rawFactor")
Jet_ID = NanoAODQuantity("Jet_jetId")
Jet_PUID = NanoAODQuantity("Jet_puId")
Jet_associatedGenJet = NanoAODQuantity("Jet_genJetIdx")
BJet_discriminator = NanoAODQuantity("Jet_btagDeepFlavB")
BJet_bRegCorr = NanoAODQuantity("Jet_bRegCorr")
BJet_bRegRes = NanoAODQuantity("Jet_bRegRes")

GenJetAK8_pt = NanoAODQuantity("GenJetAK8_pt")
GenJetAK8_eta = NanoAODQuantity("GenJetAK8_eta")
GenJetAK8_phi = NanoAODQuantity("GenJetAK8_phi")
GenJetAK8_mass = NanoAODQuantity("GenJetAK8_mass")

FatJet_eta = NanoAODQuantity("FatJet_eta")
FatJet_phi = NanoAODQuantity("FatJet_phi")
FatJet_pt = NanoAODQuantity("FatJet_pt")
FatJet_mass = NanoAODQuantity("FatJet_mass")
FatJet_msoftdrop = NanoAODQuantity("FatJet_msoftdrop")
FatJet_area = NanoAODQuantity("FatJet_area")
FatJet_flavour = NanoAODQuantity("FatJet_hadronFlavour")
FatJet_rawFactor = NanoAODQuantity("FatJet_rawFactor")
FatJet_ID = NanoAODQuantity("FatJet_jetId")
FatJet_associatedGenJet = NanoAODQuantity("FatJet_genJetAK8Idx")
FatJet_PNet_Xbb = NanoAODQuantity("FatJet_particleNetMD_Xbb")
FatJet_PNet_Xcc = NanoAODQuantity("FatJet_particleNetMD_Xcc")
FatJet_PNet_Xqq = NanoAODQuantity("FatJet_particleNetMD_Xqq")
FatJet_PNet_QCD = NanoAODQuantity("FatJet_particleNetMD_QCD")
FatJet_tau1 = NanoAODQuantity("FatJet_tau1")
FatJet_tau2 = NanoAODQuantity("FatJet_tau2")
FatJet_tau3 = NanoAODQuantity("FatJet_tau3")


Pileup_nTrueInt = NanoAODQuantity("Pileup_nTrueInt")
rho = NanoAODQuantity("fixedGridRhoFastjetAll")

GenParticle_eta = NanoAODQuantity("GenPart_eta")
GenParticle_phi = NanoAODQuantity("GenPart_phi")
GenParticle_pt = NanoAODQuantity("GenPart_pt")
GenParticle_mass = NanoAODQuantity("GenPart_mass")
GenParticle_pdgId = NanoAODQuantity("GenPart_pdgId")
GenParticle_status = NanoAODQuantity("GenPart_status")
GenParticle_statusFlags = NanoAODQuantity("GenPart_statusFlags")
GenParticle_motherid = NanoAODQuantity("GenPart_genPartIdxMother")

## Trigger Objects
TriggerObject_bit = NanoAODQuantity("TrigObj_filterBits")
TriggerObject_pt = NanoAODQuantity("TrigObj_pt")
TriggerObject_eta = NanoAODQuantity("TrigObj_eta")
TriggerObject_phi = NanoAODQuantity("TrigObj_phi")
TriggerObject_id = NanoAODQuantity("TrigObj_id")

## HTXS quantities
HTXS_Higgs_pt = NanoAODQuantity("HTXS_Higgs_pt")
HTXS_Higgs_y = NanoAODQuantity("HTXS_Higgs_y")
HTXS_njets30 = NanoAODQuantity("HTXS_njets30")
HTXS_stage_0 = NanoAODQuantity("HTXS_stage_0")
HTXS_stage_1_pTjet30 = NanoAODQuantity("HTXS_stage_1_pTjet30")
HTXS_stage1_1_fine_cat_pTjet30GeV = NanoAODQuantity("HTXS_stage1_1_fine_cat_pTjet30GeV")
HTXS_stage1_2_cat_pTjet30GeV = NanoAODQuantity("HTXS_stage1_2_cat_pTjet30GeV")
HTXS_stage1_2_fine_cat_pTjet30GeV = NanoAODQuantity("HTXS_stage1_2_fine_cat_pTjet30GeV")
LHEScaleWeight = NanoAODQuantity("LHEScaleWeight")

## MET quantities
## TODO Swich to Puppi versions for METCOV and Signifiance as soon as they are in the nanoAOD
MET_covXX = NanoAODQuantity("MET_covXX")
MET_covXY = NanoAODQuantity("MET_covXY")
MET_covYY = NanoAODQuantity("MET_covYY")
MET_significance = NanoAODQuantity("MET_significance")

MET_phi = NanoAODQuantity("PuppiMET_phi")
MET_pt = NanoAODQuantity("PuppiMET_pt")
MET_sumEt = NanoAODQuantity("PuppiMET_sumEt")

PFMET_phi = NanoAODQuantity("MET_phi")
PFMET_pt = NanoAODQuantity("MET_pt")
PFMET_sumEt = NanoAODQuantity("MET_sumEt")

## Embedding Quantities
genWeight = NanoAODQuantity("genWeight")
TauEmbedding_initialMETEt = NanoAODQuantity("TauEmbedding_initialMETEt")
TauEmbedding_initialMETphi = NanoAODQuantity("TauEmbedding_initialMETphi")
TauEmbedding_initialPuppiMETEt = NanoAODQuantity("TauEmbedding_initialPuppiMETEt")
TauEmbedding_initialPuppiMETphi = NanoAODQuantity("TauEmbedding_initialPuppiMETphi")
TauEmbedding_isMediumLeadingMuon = NanoAODQuantity("TauEmbedding_isMediumLeadingMuon")
TauEmbedding_isMediumTrailingMuon = NanoAODQuantity("TauEmbedding_isMediumTrailingMuon")
TauEmbedding_isTightLeadingMuon = NanoAODQuantity("TauEmbedding_isTightLeadingMuon")
TauEmbedding_isTightTrailingMuon = NanoAODQuantity("TauEmbedding_isTightTrailingMuon")
TauEmbedding_InitialPairCandidates = NanoAODQuantity(
    "TauEmbedding_nInitialPairCandidates"
)
TauEmbedding_SelectionOldMass = NanoAODQuantity("TauEmbedding_SelectionOldMass")
TauEmbedding_SelectionNewMass = NanoAODQuantity("TauEmbedding_SelectionNewMass")

HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ = NanoAODQuantity("HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ")
