from ..quantities import output as q
from ..quantities import nanoAOD as nanoAOD
from code_generation.producer import Producer


YHKinFit_YToBB = Producer(
    name="YHKinFit_YToBB",
    call='hhkinfit::YHKinFit({df}, {output}, {input}, "YToBB")',
    input=[
        q.pt_1,
        q.eta_1,
        q.phi_1,
        q.mass_1,
        q.pt_2,
        q.eta_2,
        q.phi_2,
        q.mass_2,
        q.bpair_pt_1,
        q.bpair_eta_1,
        q.bpair_phi_1,
        q.bpair_mass_1,
        q.bpair_pt_2,
        q.bpair_eta_2,
        q.bpair_phi_2,
        q.bpair_mass_2,
        q.met,
        q.metphi,
        q.metcov00,
        q.metcov01,
        q.metcov10,
        q.metcov11,
    ],
    output=[
        q.kinfit_convergence_YToBB,
        q.kinfit_mX_YToBB,
        q.kinfit_mY_YToBB,
        q.kinfit_mh_YToBB,
        q.kinfit_chi2_YToBB,
        q.kinfit_prob_YToBB,
        q.kinfit_pull1_YToBB,
        q.kinfit_pull2_YToBB,
        q.kinfit_pullBalance_YToBB,
    ],
    scopes=["mt", "et", "tt"],
)

YHKinFit_YToTauTau = Producer(
    name="YHKinFit_YToTauTau",
    call='hhkinfit::YHKinFit({df}, {output}, {input}, "YToTauTau")',
    input=[
        q.pt_1,
        q.eta_1,
        q.phi_1,
        q.mass_1,
        q.pt_2,
        q.eta_2,
        q.phi_2,
        q.mass_2,
        q.bpair_pt_1,
        q.bpair_eta_1,
        q.bpair_phi_1,
        q.bpair_mass_1,
        q.bpair_pt_2,
        q.bpair_eta_2,
        q.bpair_phi_2,
        q.bpair_mass_2,
        q.met,
        q.metphi,
        q.metcov00,
        q.metcov01,
        q.metcov10,
        q.metcov11,
    ],
    output=[
        q.kinfit_convergence_YToTauTau,
        q.kinfit_mX_YToTauTau,
        q.kinfit_mY_YToTauTau,
        q.kinfit_mh_YToTauTau,
        q.kinfit_chi2_YToTauTau,
        q.kinfit_prob_YToTauTau,
        q.kinfit_pull1_YToTauTau,
        q.kinfit_pull2_YToTauTau,
        q.kinfit_pullBalance_YToTauTau,
    ],
    scopes=["mt", "et", "tt"],
)

YHKinFit_YToBB_boosted = Producer(
    name="YHKinFit_YToBB_boosted",
    call='hhkinfit::YHKinFit({df}, {output}, {input}, "YToBB")',
    input=[
        q.boosted_pt_1,
        q.boosted_eta_1,
        q.boosted_phi_1,
        q.boosted_mass_1,
        q.boosted_pt_2,
        q.boosted_eta_2,
        q.boosted_phi_2,
        q.boosted_mass_2,
        q.bpair_pt_1_boosted,
        q.bpair_eta_1_boosted,
        q.bpair_phi_1_boosted,
        q.bpair_mass_1_boosted,
        q.bpair_pt_2_boosted,
        q.bpair_eta_2_boosted,
        q.bpair_phi_2_boosted,
        q.bpair_mass_2_boosted,
        q.met_boosted,
        q.metphi_boosted,
        q.metcov00,
        q.metcov01,
        q.metcov10,
        q.metcov11,
    ],
    output=[
        q.kinfit_convergence_YToBB_boosted,
        q.kinfit_mX_YToBB_boosted,
        q.kinfit_mY_YToBB_boosted,
        q.kinfit_mh_YToBB_boosted,
        q.kinfit_chi2_YToBB_boosted,
        q.kinfit_prob_YToBB_boosted,
        q.kinfit_pull1_YToBB_boosted,
        q.kinfit_pull2_YToBB_boosted,
        q.kinfit_pullBalance_YToBB_boosted,
    ],
    scopes=["mt", "et", "tt"],
)

YHKinFit_YToTauTau_boosted = Producer(
    name="YHKinFit_YToTauTau_boosted",
    call='hhkinfit::YHKinFit({df}, {output}, {input}, "YToTauTau")',
    input=[
        q.boosted_pt_1,
        q.boosted_eta_1,
        q.boosted_phi_1,
        q.boosted_mass_1,
        q.boosted_pt_2,
        q.boosted_eta_2,
        q.boosted_phi_2,
        q.boosted_mass_2,
        q.bpair_pt_1_boosted,
        q.bpair_eta_1_boosted,
        q.bpair_phi_1_boosted,
        q.bpair_mass_1_boosted,
        q.bpair_pt_2_boosted,
        q.bpair_eta_2_boosted,
        q.bpair_phi_2_boosted,
        q.bpair_mass_2_boosted,
        q.met_boosted,
        q.metphi_boosted,
        q.metcov00,
        q.metcov01,
        q.metcov10,
        q.metcov11,
    ],
    output=[
        q.kinfit_convergence_YToTauTau_boosted,
        q.kinfit_mX_YToTauTau_boosted,
        q.kinfit_mY_YToTauTau_boosted,
        q.kinfit_mh_YToTauTau_boosted,
        q.kinfit_chi2_YToTauTau_boosted,
        q.kinfit_prob_YToTauTau_boosted,
        q.kinfit_pull1_YToTauTau_boosted,
        q.kinfit_pull2_YToTauTau_boosted,
        q.kinfit_pullBalance_YToTauTau_boosted,
    ],
    scopes=["mt", "et", "tt"],
)